### ISSUE TITLE
Hinzufügen eines neuen Fensters zur Anzeige des Scoreboards oder Spielmodus in BuzzMaster

### ISSUE THREAD

**Issue by obsidian0815** [marvin-wtt/BuzzMaster#18]
---

**Beschreibung:**

Um die Benutzererfahrung in BuzzMaster weiter zu verbessern und den Spielern eine zusätzliche Informationsquelle zur Verfügung zu stellen, schlagen wir vor, ein neues Fenster hinzuzufügen, das ausschließlich zur Anzeige des Scoreboards oder des aktuellen Spielmodus dient. Dieses Fenster soll keine Benutzeroberfläche (UI) enthalten, sondern nur die relevanten Informationen in einem übersichtlichen Format anzeigen.

**Funktionalität des neuen Fensters:**

Das neue Fenster soll folgende Funktionen unterstützen:

1. **Anzeige des Scoreboards:** Das Fenster soll in Echtzeit das aktuelle Scoreboard anzeigen, einschließlich der Punktzahlen der einzelnen Spieler und Teams.

2. **Anzeige des Spielmodus:** Falls gewünscht, kann das Fenster auch den aktuellen Spielmodus anzeigen, um den Spielern eine klare Übersicht über die Spielregeln und Ziele zu bieten.

**Implementierungsdetails:**

Das neue Fenster soll ohne Benutzeroberfläche auskommen und stattdessen die Scoreboard- oder Spielmodusinformationen direkt anzeigen. Dies kann beispielsweise durch die Verwendung von Textausgaben oder einfachen Grafiken erfolgen, um eine klare und leicht verständliche Darstellung zu gewährleisten.

**Vorteile des neuen Fensters:**

- **Verbesserte Übersichtlichkeit:** Spieler können jederzeit auf die relevanten Spielinformationen zugreifen, ohne die Hauptbenutzeroberfläche zu verlassen.
- **Effiziente Nutzung des Bildschirmplatzes:** Durch die Integration eines dedizierten Fensters für das Scoreboard oder den Spielmodus kann der verfügbare Bildschirmplatz optimal genutzt werden.
- **Flexibilität und Erweiterbarkeit:** Die Implementierung eines separaten Fensters ermöglicht es uns, zukünftige Erweiterungen und Verbesserungen leichter zu integrieren.

**Umsetzungsplan:**

1. **Anforderungsanalyse:** Bestimmung der genauen Anforderungen an das neue Fenster sowie Festlegung der gewünschten Funktionalitäten.
   
2. **Implementierung:** Entwicklung des neuen Fensters gemäß den definierten Anforderungen, unter Berücksichtigung der bestehenden Architektur und Codebasis von BuzzMaster.

3. **Test und Validierung:** Umfassende Tests, um die korrekte Funktionalität und Zuverlässigkeit des neuen Fensters sicherzustellen, einschließlich Integrationstests mit anderen Komponenten von BuzzMaster.

4. **Deployment:** Bereitstellung des neuen Fensters in einer kontrollierten Umgebung, gefolgt von einer Überwachung und Fehlerbehebung während des Rollouts.

**Zusammenfassung:**

Die Implementierung eines neuen Fensters zur Anzeige des Scoreboards oder Spielmodus wird die Benutzererfahrung in BuzzMaster verbessern und den Spielern eine zusätzliche Informationsquelle bieten. Wir bitten daher um Unterstützung bei der Umsetzung dieses Features, um die Attraktivität und Funktionalität unserer Plattform weiter zu steigern.

---

*Hinweis: Bei Fragen oder Anregungen stehe ich gerne zur Verfügung. Vielen Dank für Ihre Mitarbeit!*

**Comment by marvin-wtt** [comment]
See #35
