### ISSUE TITLE
lock controller on start of question

### ISSUE THREAD

**Issue by McMoerlin** [marvin-wtt/BuzzMaster#42]
when a question is started (Buzzer, Quiz, Stopwatch) lock the current number of dongels/controller, so that new connected dongles cant play in a currently running question. Reset the list for the next Question.

Can new Buzzers play a Re-Open in Buzzer question?
How should disconnected dongles be treated?

**Comment by marvin-wtt** [comment]
Maybe we just add a note to the README explaining the PnP behavior. State transitions do not happen anymore with the latest version.
