### ISSUE TITLE
option for ps2 Buzzer to get the right driver

### ISSUE THREAD

**Issue by McMoerlin** [marvin-wtt/BuzzMaster#48]

**Comment by marvin-wtt** [comment]
The PS2 dongles require a manual driver change, as described in the README. 
The driver change within the app is only possible with elevated permissions. 

Perhaps it's possible to add a PowerShell file that performs this action.

**Comment by marvin-wtt** [comment]
Drivers can not be changed using PnPUtlils. Creating a custom `.inf` file is not possible without code signing.

**Comment by McMoerlin** [comment]
Thought progress stopped.

You can find the PS2 dongles with the wrong driver with the following command:

Get-WmiObject Win32_PnPEntity | Where-Object DeviceID -Match "^USB\\VID_054C.*"

But it seems there is no solution to change the driver to HID
